services:
    redis:
        image: 'redis:alpine'

    # mysql:
    #     image: 'mysql:8.0'
    #     volumes:
    #         - /usr/local/mysql:/var/lib/mysql
    #     environment:
    #         MYSQL_ROOT_PASSWORD: 'test_pass'
    #         MYSQL_USER: 'test'
    #         MYSQL_PASS: 'pass'
    #     ports:
    #         - '1801:3306'  

    webserver:
        image: 'nginx:alpine'
        volumes:
            - './nginx/sites-available/:/etc/nginx/conf.d/'
            - './nginx/logs:/var/log/nginx'  # Nginx 日志路径
        ports:
            - '80:80'

    php8.1:
        build: ../config/php82
        container_name: php8.2
        volumes:
        - '${PROJECT_DOCUMENT_ROOT}/:/baifu'
        - ../config/php82/php.ini:/usr/local/etc/php/php.ini
        - ../config/php82/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf
        - ../logs/php82/:/var/log/php-fpm/
        - ../config/php82/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:ro
        ports:
        - 9081:9000