services:
    redis:
        image: 'redis:alpine'

    mysql:
        image: 'mysql:8.0'
        volumes:
            - /usr/local/mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: 'test_pass'
            MYSQL_USER: 'test'
            MYSQL_PASS: 'pass'
        ports:
            - '1801:3306'  

    webserver:
        image: 'nginx:alpine'
        volumes:
            - '${PROJECT_DOCUMENT_ROOT}/:/baifu'
            - './nginx/sites-available/:/etc/nginx/conf.d/'
            - './nginx/logs:/var/log/nginx'  # Nginx 日志路径
        ports:
            - '80:80'

    php8.1:
        build: ../config/php81
        container_name: php8.1
        volumes:
        - '${PROJECT_DOCUMENT_ROOT}/:/baifu'
        - ../config/php81/php.ini:/usr/local/etc/php/php.ini
        - ../config/php81/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf
        - ../logs/php81/:/var/log/php-fpm/
        - ../config/php81/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:ro
        ports:
        - 9081:9000